import {Route,Routes} from "react-router-dom"
import {AppLayout} from "@/components/layout/app-layout"
import {ProtectedRoute} from "@/components/layout/protected-route"
import {AddTripPage} from "@/pages/add-trip"
import {AdminAnalyticsPage} from "@/pages/admin-analytics"
import {DashboardPage} from "@/pages/dashboard"
import {EditTripPage} from "@/pages/edit-trip"
import {NotFoundPage} from "@/pages/not-found"
import {ProfilePage} from "@/pages/profile"
import {PublicSharePage} from "@/pages/public-share"
import {SettingsPage} from "@/pages/settings"
import {TripChecklistPage} from "@/pages/trip-checklist"
import {TripDetailPage} from "@/pages/trip-detail"
import {TripItineraryPage} from "@/pages/trip-itinerary"
import {TripJournalPage} from "@/pages/trip-journal"
import {WelcomePage} from "@/pages/welcome"
export function App(){return <Routes><Route path="/" element={<WelcomePage/>}/><Route path="/share/:shareId" element={<PublicSharePage/>}/><Route element={<ProtectedRoute><AppLayout/></ProtectedRoute>}><Route path="/dashboard" element={<DashboardPage/>}/><Route path="/add-trip" element={<AddTripPage/>}/><Route path="/edit-trip/:id" element={<EditTripPage/>}/><Route path="/trip/:id" element={<TripDetailPage/>}/><Route path="/trip/:id/itinerary" element={<TripItineraryPage/>}/><Route path="/trip/:id/checklist" element={<TripChecklistPage/>}/><Route path="/trip/:id/journal" element={<TripJournalPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/profile" element={<ProfilePage/>}/></Route><Route path="/admin/analytics" element={<ProtectedRoute adminOnly><AppLayout/></ProtectedRoute>}><Route index element={<AdminAnalyticsPage/>}/></Route><Route path="*" element={<NotFoundPage/>}/></Routes>}
